# Generated by Django 5.0.6 on 2024-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmovi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('originalni_naziv', models.CharField(max_length=120)),
                ('slug', models.SlugField(default='')),
                ('godina', models.CharField(max_length=120)),
                ('imdb_ocena', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('link_za_gledanje', models.CharField(default='', max_length=320)),
                ('image', models.FileField(upload_to='movie-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
