# Generated by Django 5.0.6 on 2024-06-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmovi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmovi',
            name='zanr',
            field=models.CharField(default='', max_length=120),
        ),
    ]
