# Generated by Django 5.0.6 on 2024-06-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serije', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epizoda',
            name='epizode_preuzmi',
        ),
    ]
