# Generated by Django 5.0.6 on 2024-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serije', '0002_remove_epizoda_epizode_preuzmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='epizoda',
            name='epizode_preuzmi',
            field=models.CharField(default='', max_length=300),
        ),
    ]
