# Generated by Django 5.0.6 on 2024-06-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serije', '0003_epizoda_epizode_preuzmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='serije',
            name='zanr',
            field=models.CharField(default='', max_length=120),
        ),
    ]
